version: '3'

services:
  phalcon_nginx:
    image: nginx:latest
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 7000:7000
    links:
      - phalcon_sites

  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/

  phalcon_sites:
    build: ./sites
    restart: always
    working_dir: /var/www/sites
    links:
      - phalcon_users
    volumes:
      - ./sites:/var/www/sites

  phalcon_users:
    build: ./users
    restart: always
    working_dir: /var/www/users
    links:
      - sqlite3
    volumes:
      - ./users:/var/www/users
